### ISSUE TITLE
Puppet run fails on File resource for data directory

### ISSUE THREAD

**Issue by lairsdragon** [elasticsearch/puppet-elasticsearch#243]
I have the following snippet in my manifest for elasticsearch deployment and get an error about the File resource on the regular puppet runs. The first setup run works as expected.  

From my understanding the error comes from the `recurse => true` attribute since the File resource traverses the data directory and some files/dirs changes while the traversal is running. Why is the recurse attribute needed?

```puppet
  class {'elasticsearch':
    version => '1.4.2',
    java_install => true,
    init_defaults => $logserver_config,
    datadir => '/var/lib/elasticsearch-data',
    config => {
      'cluster.name' => "elasticsearch-$location",
      'http.cors.enabled' => 'enabled',
      'http.cors.allow-credentials' => 'enabled',
#      'http.cors.allow-origin' => '*',
    },
  }
  ->
  elasticsearch::instance { 'ls01':,
  }
```
Error Message:
```
(/Stage[main]/Elasticsearch::Config/File[/var/lib/elasticsearch-data]) Failed to generate additional resources using 'eval_generate: No such file 
or directory - /var/lib/elasticsearch-data/ls01/elasticsearch-bb/nodes/0/indices/.marvel-2015.01.21/0/index/_6d2.fdx
```

**Comment by electrical** [comment]
Hi,

the recurse attribute is for ensuring all files belong to the right user if a custom user is given.
Could you remove the explicit order '->' it shouldn't be required as the module already takes care of that internally.

**Comment by lairsdragon** [comment]
OK, I understand the reason for using recurse, but sadly the this leads to the mentioned error nearly for every puppet run. For the setup phase I see a good reason for this but not for the runtime phase. If the files below my data dir have the wrong user, I have a general problem in the setup which could not be fixed by changing all user id of all files below the data directory...

I have also removed the explicit order, but that does not change the behaviour.

**Comment by electrical** [comment]
Very weird you are seeing this issue as i haven't seen this with any of my tests.
It is possible that with the recurse option it first finds all possible files and then does the changes and then in the meantime elasticsearch it self has done something with the files ( merge it into other segments for example )
Not using recurse means that if you would be switching users the data dir won't be changed correctly.
But then again, who would change it after already running ES.

I'll see if i can fix this issue.

**Comment by lairsdragon** [comment]
Maybe for the purpose of being sure that the right user is owning the files a exec 'chmod -R' would be more feasible in this case..

**Comment by lairsdragon** [comment]
I've testet the whole setup with 3.7.3puppetlabs1 from the puppet repo and I was not able to reproduce this problem. Since puppet 2 moves slowly to deprecation, I like to close this issue..

**Comment by lairsdragon** [comment]
Tried it also with puppet 3.7.3 and problem persists. 

```
Error: /Stage[main]/Elasticsearch::Config/File[/var/lib/elasticsearch-data]: Failed to generate additional resources using 'eval_generate': No such file or directory - /var/lib/elasticsearch-data/ls01/elasticsearch-bb/nodes/0/indices/logstash-2015.01.21/0/index/_9pj.fdx
Error: /Stage[main]/Ic3s-logging::Server/Elasticsearch::Instance[ls01]/File[/var/lib/elasticsearch-data/ls01]: Failed to generate additional resources using 'eval_generate': No such file or directory - /var/lib/elasticsearch-data/ls01/elasticsearch-bb/nodes/0/indices/logstash-2015.01.21/1/index/_9py.fdt
````

**Comment by electrical** [comment]
Okay. I think its a race condition for the 2 stages that recurse works.
First it finds all the files and dirs it needs to manage. then it creates the resources to change them.
It seems that in the time between the discovery and changes some files got changed.
I'll remove the recurse option so we atleast manage the main data dir.

**Comment by electrical** [comment]
@lairsdragon could you try out a possible fix with PR https://github.com/elasticsearch/puppet-elasticsearch/pull/247 ?

**Comment by electrical** [comment]
did some local testing.
The PR allows the module to manage the data directory it self but not the files within the data dir.
That should solve your issue.
Will merge this tomorrow unless you find an issue with this.

**Comment by talisto** [comment]
I just hit this same issue (or a similar issue), even on the 0.9.0 version.  The error I was getting (repeatedly) was: 
```
Error: /Stage[main]/Elasticsearch::Config/File[/usr/share/elasticsearch]: Failed to generate additional resources using 'eval_generate': No such file or directory - /usr/share/elasticsearch/data/es-01/elasticsearch/nodes/0/indices/logstash-2015.02.06/0/index/_ah.fdx
```
I removed the `recurse => true` parameter from the `file { $elasticsearch::params::homedir: }` resource in `config.pp` which resolved the issue.

**Comment by electrical** [comment]
@talisto that is worrying, i had hoped that the 0.9.0 release would have solved it by setting explicit recurse to false on the other parts.
I'll re-open this issue an chase it.

**Comment by electrical** [comment]
@talisto I've created PR https://github.com/elasticsearch/puppet-elasticsearch/pull/263
Would you be able to test it out and see if this fixes your issue?

**Comment by talisto** [comment]
Ok, I've applied your PR and it seems to be all good (my puppet agent applies the manifest just fine), however the problem occurred intermittently, so I can't say that it is definitively fixed.  I'm assuming it is though!

**Comment by electrical** [comment]
@talisto sorry for not getting back sooner, been on holiday.
I've merged the PR and will do a release this week.
thanks for testing!

**Comment by nivrozen** [comment]
hi,

i know this is an old thread, but it seems like the issue still exists. getting this error on all my ES nodes:
Error: /Stage[main]/Elasticsearch::Webeyez/Elasticsearch::Instance[webeyez]/File[/data]: Failed to generate additional resources using 'eval_generate': No such file or directory - /data/webeyez/nodes/0/indices/.marvel-2015.12.31/0/index/_m4x.fdx

any clue how to resolve this?
thanks,

**Comment by siliconalchemy** [comment]
+1 started happening since I upgraded to ES 2.1.1 and latest git code for this module

**Comment by siliconalchemy** [comment]
Changing recurse=>true to recurse=>false on line 214 in instance.pp (in file { $instance_datadir}), but that's probably not a correct fix.

**Comment by electrical** [comment]
@siliconalchemy it most likely will be a good and i will most likely implement that soon.
